# Generated by Django 3.1.6 on 2021-02-20 07:41

import data.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('lead_time', models.PositiveIntegerField(blank=True, default='0', null=True, validators=[data.models.validate_zero])),
                ('service_level', models.PositiveIntegerField(blank=True, default='0', null=True, validators=[data.models.validate_even])),
                ('standard_deviation', models.PositiveIntegerField(blank=True, default='0', null=True)),
                ('carrying_cost', models.PositiveIntegerField(default='0', help_text='Enter as percentage of unit cost', validators=[data.models.validate_even])),
                ('ordering_cost', models.PositiveIntegerField(default='0', null=True)),
                ('unit_costprice', models.PositiveIntegerField(default='0', null=True, validators=[data.models.validate_zero])),
                ('average_daily_demand', models.PositiveIntegerField(default='0', null=True)),
                ('total_inventory', models.IntegerField(blank=True, default='0', null=True)),
                ('eoq', models.IntegerField(blank=True, default='0', null=True)),
                ('no_of_workingdays', models.IntegerField(blank=True, default='0', null=True)),
                ('rq', models.IntegerField(blank=True, default='0', null=True)),
                ('z', models.DecimalField(blank=True, decimal_places=3, default='0', max_digits=4, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_quantity', models.IntegerField(null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('recieve_quantity', models.IntegerField(default='0', null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demands', to='data.items')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='demand', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
