# Generated by Django 3.1.6 on 2021-02-22 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('csvs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uplo', to=settings.AUTH_USER_MODEL),
        ),
    ]
