# Generated by Django 3.1.6 on 2021-03-04 04:54

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210221_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carrying_cost',
            field=models.PositiveIntegerField(default='12', help_text='Enter as percentage of unit cost', validators=[products.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='product',
            name='no_of_workingdays',
            field=models.IntegerField(blank=True, default='300', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='service_level',
            field=models.PositiveIntegerField(blank=True, default='90', null=True, validators=[products.models.validate_even]),
        ),
        migrations.AlterField(
            model_name='product',
            name='standard_deviation',
            field=models.PositiveIntegerField(blank=True, default='5', null=True),
        ),
    ]
